# Protocol: create_doc_chain
# Create full documentation chain for a module from templates

protocol: create_doc_chain
version: "1.1"
description: Create full documentation chain for a module from templates

triggers:
  - gap: "Module exists without documentation"
  - event: "New module being scaffolded"

requires_skills:
  - SKILL_Create_Module_Documentation_Chain_From_Templates_And_Seed_Todos.md

contextual_knowledge:
  domain: |
    Doc chain: PATTERNS → BEHAVIORS → ALGORITHM → VALIDATION → IMPLEMENTATION → HEALTH → SYNC.
    Each doc type has specific purpose and template.
    Creates narratives in graph linked to space.
    Seeds @ngram:TODO for each doc to be filled.

  constraints: |
    - Must create all doc types (complete chain)
    - Each doc gets at least one TODO
    - Creates graph narratives, not just files

  dependencies: |
    Requires: space exists
    Enables: structured documentation, canon establishment

  quality_criteria: |
    Good: "Created 7 doc narratives with 7 TODOs seeded"
    Bad: "Made some docs"

steps:
  load_context:
    type: query
    auto_fetch:
      - query: { find: narrative, in_space: "{space}" }
        store_as: existing_docs
    next: check_exists

  check_exists:
    type: branch
    checks:
      - condition: "{existing_docs | has_all_doc_types}"
        action:
          type: complete
          message: "Doc chain already exists for {space}"
      - condition: "ready"
        action: { goto: gather_details }

  gather_details:
    type: ask
    context: |
      {contextual_knowledge.domain}

      Space: {space}
      Existing docs: {existing_docs | list by type}

    questions:
      - name: module_name
        ask: "Module name for doc titles?"
        expects: { type: string }

      - name: initial_patterns_notes
        ask: "Any initial design notes for PATTERNS?"
        expects: { type: string, min_length: 0 }

      - name: known_behaviors
        ask: "Any known behaviors to document?"
        expects: { type: string, min_length: 0 }

    next: gather_thoughts

  gather_thoughts:
    type: ask
    context: |
      ## Protocol Reflection

      Before creating the doc chain, share any thoughts on this protocol.
      Your feedback helps improve future executions.

    questions:
      - name: protocol_thoughts
        ask: "Any thoughts or suggestions on how to improve this create_doc_chain protocol?"
        why_it_matters: "Continuous improvement through reflection"
        good_answer: "Could auto-populate templates with skeleton structure based on module type. E.g., API modules get standard endpoint documentation pattern."
        expects:
          type: string
          required: false

      - name: context_observations
        ask: "Anything about the context or process that could be better?"
        expects:
          type: string
          required: false

    next: create_doc_chain

  create_doc_chain:
    type: create
    nodes:
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: PATTERNS Doc
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "doc_patterns_{space}"
        node_type: narrative
        type: patterns
        name: "PATTERNS_{module_name}"
        content: "{initial_patterns_notes}"
        todo: "@ngram:TODO Fill design decisions and rationale"
        weight: 0.7
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # id: "doc_patterns_{space}"
        #   WHAT: Unique identifier linking doc to space
        #   WHY: Enables querying "get PATTERNS doc for space X"
        #   FORMAT: doc_{type}_{space_id}
        #
        # node_type: narrative
        #   WHAT: Persistent documentation node
        #   WHY: Narratives are long-lived (vs moments = events)
        #   CONTRAST: moments track events, narratives track knowledge
        #
        # type: patterns
        #   WHAT: Doc chain type - design philosophy
        #   WHY: Explains WHY module exists, WHAT's in/out of scope
        #   LOADED: Before modifying module architecture
        #
        # name: "PATTERNS_{module_name}"
        #   WHAT: Display name matching file naming convention
        #   WHY: Consistency with filesystem docs
        #   EXAMPLE: "PATTERNS_Physics_Tick_Runner"
        #
        # content: "{initial_patterns_notes}"
        #   WHAT: Initial design notes or empty string
        #   WHY: Seed with existing knowledge if available
        #   UPDATES: Via separate update protocols
        #
        # todo: "@ngram:TODO ..."
        #   WHAT: Actionable marker for next agent
        #   WHY: Makes explicit what needs filling
        #   FORMAT: @ngram:TODO {action}
        #
        # weight: 0.7
        #   WHAT: Importance score for graph queries
        #   WHY: PATTERNS is high priority (0.7) - defines shape
        #   RANGE: 0.6-0.7 for core docs, 0.5 for todos

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: BEHAVIORS Doc
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "doc_behaviors_{space}"
        node_type: narrative
        type: behaviors
        name: "BEHAVIORS_{module_name}"
        content: "{known_behaviors}"
        todo: "@ngram:TODO Document observable effects"
        weight: 0.7
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # type: behaviors
        #   WHAT: Doc chain type - observable effects
        #   WHY: Describes WHAT module does externally
        #   LOADED: When behavior unclear or testing

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: ALGORITHM Doc
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "doc_algorithm_{space}"
        node_type: narrative
        type: algorithm
        name: "ALGORITHM_{module_name}"
        content: ""
        todo: "@ngram:TODO Document procedures and pseudocode"
        weight: 0.7
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # type: algorithm
        #   WHAT: Doc chain type - procedures and logic
        #   WHY: Explains HOW module works (pseudocode)
        #   LOADED: When implementing or debugging logic

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: VALIDATION Doc
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "doc_validation_{space}"
        node_type: narrative
        type: validation_doc
        name: "VALIDATION_{module_name}"
        content: ""
        todo: "@ngram:TODO Define invariants"
        weight: 0.7
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # type: validation_doc
        #   WHAT: Doc chain type - invariants
        #   WHY: Defines WHAT must always be true
        #   LOADED: Before implementing to establish constraints

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: IMPLEMENTATION Doc
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "doc_implementation_{space}"
        node_type: narrative
        type: implementation_doc
        name: "IMPLEMENTATION_{module_name}"
        content: ""
        todo: "@ngram:TODO Map code surfaces and docking points"
        weight: 0.7
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # type: implementation_doc
        #   WHAT: Doc chain type - code architecture
        #   WHY: Maps WHERE code lives, data flows
        #   LOADED: When building or navigating codebase

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: HEALTH Doc
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "doc_health_{space}"
        node_type: narrative
        type: health_doc
        name: "HEALTH_{module_name}"
        content: ""
        todo: "@ngram:TODO Define health indicators"
        weight: 0.7
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # type: health_doc
        #   WHAT: Doc chain type - health checks
        #   WHY: Defines WHAT gets verified in practice
        #   LOADED: When defining health signals

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: SYNC Doc
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "doc_sync_{space}"
        node_type: narrative
        type: sync
        name: "SYNC_{module_name}"
        status: "DESIGNING"
        content: "Doc chain created, all docs need filling."
        todo: "@ngram:TODO Update as work progresses"
        weight: 0.6
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # type: sync
        #   WHAT: Doc chain type - current state
        #   WHY: Tracks WHERE we are, handoffs, recent changes
        #   LOADED: Always (first doc to read)
        #
        # status: "DESIGNING"
        #   WHAT: Maturity state of module
        #   WHY: Signals this is work-in-progress
        #   OPTIONS: CANONICAL, DESIGNING, PROPOSED, DEPRECATED
        #
        # weight: 0.6
        #   WHAT: Slightly lower than other docs
        #   WHY: SYNC is current state, others are canonical knowledge

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: Moment (Creation Event)
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "moment_create_doc_chain_{timestamp}"
        node_type: moment
        type: protocol_create
        prose: "Created doc chain for {module_name} with 7 documents"
        status: completed
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # id: "moment_create_doc_chain_{timestamp}"
        #   WHAT: Unique ID with timestamp for ordering
        #   WHY: Moments are ordered chronologically
        #   FORMAT: moment_{action}_{timestamp}
        #
        # node_type: moment
        #   WHAT: Point-in-time event record
        #   WHY: Creates history that can be queried
        #   CONTRAST: narratives persist, moments record events
        #
        # type: protocol_create
        #   WHAT: Categorizes this moment type
        #   WHY: Enables queries like "show all creation events"
        #   OTHER_TYPES: sync_update, decision, escalation_raised
        #
        # prose: "Created doc chain..."
        #   WHAT: Human-readable description
        #   WHY: Displayed in activity feeds and history
        #   FORMAT: Past tense, specific about what happened
        #
        # status: completed
        #   WHAT: Moment completion state
        #   WHY: Tracks whether action finished successfully
        #   OPTIONS: completed, pending, failed

    links:
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # LINK: Space Contains Docs
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - type: contains
        from: "{space}"
        to: "doc_patterns_{space}"
        # ━━━ LINK EXPLANATION ━━━
        #
        # type: contains
        #   WHAT: Hierarchical ownership relationship
        #   WHY: Establishes "space owns this doc"
        #   QUERY: "What docs are in space X?" follows contains
        #   DIRECTION: from=container, to=contained
        #   NOTE: Each doc gets its own contains link to space
      - type: contains
        from: "{space}"
        to: "doc_behaviors_{space}"
      - type: contains
        from: "{space}"
        to: "doc_algorithm_{space}"
      - type: contains
        from: "{space}"
        to: "doc_validation_{space}"
      - type: contains
        from: "{space}"
        to: "doc_implementation_{space}"
      - type: contains
        from: "{space}"
        to: "doc_health_{space}"
      - type: contains
        from: "{space}"
        to: "doc_sync_{space}"

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # LINK: Actor Expresses Moment
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - type: expresses
        from: "{actor_id}"
        to: "moment_create_doc_chain_{timestamp}"
        # ━━━ LINK EXPLANATION ━━━
        #
        # type: expresses
        #   WHAT: Attribution link
        #   WHY: Records who/what created this moment
        #   QUERY: "What did agent X do?" follows expresses
        #   DIRECTION: from=actor, to=moment

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # LINK: Moment About Space
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - type: about
        from: "moment_create_doc_chain_{timestamp}"
        to: "{space}"
        # ━━━ LINK EXPLANATION ━━━
        #
        # type: about
        #   WHAT: Topic/subject relationship
        #   WHY: Records what the moment relates to
        #   QUERY: "What happened to space X?" follows about
        #   DIRECTION: from=moment/narrative, to=subject

    next: call_handoff

  call_handoff:
    type: call_protocol
    protocol: completion_handoff
    inputs:
      space_id: "{space}"
      task_id: "create_doc_chain_{space}"
    next: $complete

output:
  docs_created:
    - "doc_patterns_{space}"
    - "doc_behaviors_{space}"
    - "doc_algorithm_{space}"
    - "doc_validation_{space}"
    - "doc_implementation_{space}"
    - "doc_health_{space}"
    - "doc_sync_{space}"
  todos_seeded: 7
  moment: "moment_create_doc_chain_{timestamp}"
