# Protocol: define_space
# Create a space/container node for a module

protocol: define_space
version: "1.1"
description: Create a space/container node for a module

triggers:
  - gap: "Module needs container in graph"
  - event: "New module being created"

requires_skills: []

contextual_knowledge:
  domain: |
    Spaces are containers for module content.
    Space types: module, area, concept, project.
    Spaces contain: narratives, things, moments.
    Spaces link to parent spaces via CONTAINS.

  constraints: |
    - Space ID must be unique
    - Should specify type and parent
    - Creates container for all module content

  dependencies: |
    Requires: nothing (can be first node)
    Enables: all other protocols (they need a space to work in)

  quality_criteria: |
    Good: "space_physics_tick with type=module, parent=space_physics"
    Bad: "some_space"

steps:
  check_exists:
    type: query
    auto_fetch:
      - query: { find: space, where: { id: "{space_id}" } }
        store_as: existing
    next: branch_exists

  branch_exists:
    type: branch
    checks:
      - condition: "{existing | count} > 0"
        action:
          type: complete
          message: "Space {space_id} already exists"
      - condition: "ready"
        action: { goto: gather_details }

  gather_details:
    type: ask
    context: |
      {contextual_knowledge.domain}

      Creating new space.

      ID Convention: {node-type}_{SUBTYPE}_{instance}
      Example: space_MODULE_engine-physics

    questions:
      - name: module_name
        ask: "Module name? (noun, lowercase, dashes for multi-word)"
        why_it_matters: "Used to generate space ID: space_MODULE_{module_name}"
        good_answer: "physics-tick-runner"
        bad_answer: "my_space"
        expects:
          type: string
          pattern: "^[a-z][a-z0-9-]*$"

      - name: space_name
        ask: "Human-readable name?"
        why_it_matters: "Display name in UI and documentation"
        good_answer: "Physics Tick Runner"
        expects: { type: string }

      - name: space_type
        ask: "Space type?"
        why_it_matters: |
          Determines how space is treated:
          - module: Code + docs for a single component
          - area: Grouping of related modules
          - concept: Cross-cutting idea that spans modules
          - project: Top-level container
        expects:
          type: enum
          options: [module, area, concept, project]

      - name: parent_space
        ask: "Parent space ID? (empty if root)"
        why_it_matters: "Establishes containment hierarchy for navigation"
        good_answer: "space_AREA_physics"
        expects: { type: string, min_length: 0 }

      - name: description
        ask: "Brief description of what this space contains?"
        why_it_matters: "Helps agents understand scope when loading context"
        good_answer: "Manages the tick-based execution loop for physics simulation. Handles timing, iteration, and state updates."
        expects: { type: string }

    # Auto-generate space_id from inputs
    computed:
      space_id: "space_{space_type | upper}_{module_name}"
      # Examples:
      #   module_name=physics-tick-runner, space_type=module → space_MODULE_physics-tick-runner
      #   module_name=engine, space_type=area → space_AREA_engine

    next: gather_thoughts

  gather_thoughts:
    type: ask
    context: |
      ## Protocol Reflection

      Before creating the space, share any thoughts on this protocol.
      Your feedback helps improve future executions.

    questions:
      - name: protocol_thoughts
        ask: "Any thoughts or suggestions on how to improve this define_space protocol?"
        why_it_matters: "Continuous improvement through reflection"
        good_answer: "Could auto-suggest parent_space based on space_id pattern. E.g., space_physics_tick → suggest parent space_physics"
        expects:
          type: string
          required: false

      - name: context_observations
        ask: "Anything about the context or process that could be better?"
        expects:
          type: string
          required: false

    next: create_space

  create_space:
    type: create
    nodes:
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: Space (Container)
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "{space_id}"
        node_type: space
        name: "{space_name}"
        type: "{space_type}"
        description: "{description}"
        weight: 1.0
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # id: "{space_id}"
        #   WHAT: Unique identifier like "space_physics_tick"
        #   WHY: Used in all graph queries to find this space
        #   FORMAT: space_<area>_<module> for consistency
        #
        # node_type: space
        #   WHAT: Declares this as a container node
        #   WHY: Spaces can contain narratives, things, moments
        #   ALTERNATIVES: narrative, thing, moment, todo
        #
        # name: "{space_name}"
        #   WHAT: Human-readable display name
        #   WHY: Shown in UI, docs, and search results
        #   EXAMPLE: "Physics Tick Runner"
        #
        # type: "{space_type}"
        #   WHAT: Categorization within spaces
        #   WHY: Affects how space is treated in queries/views
        #   OPTIONS:
        #     - module: Single component with code + docs
        #     - area: Grouping of modules
        #     - concept: Cross-cutting idea
        #     - project: Top-level container
        #
        # description: "{description}"
        #   WHAT: Brief explanation of space contents
        #   WHY: Helps agents decide whether to load this context
        #   LENGTH: 1-3 sentences, specific not vague
        #
        # weight: 1.0
        #   WHAT: Importance score (0.0-1.0)
        #   WHY: Spaces are always max weight (1.0) - they're containers
        #   RANGE: 1.0 for spaces, 0.1-0.9 for contents

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # NODE: Moment (Creation Event)
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - id: "moment_CREATE_{module_name}_{timestamp_short}"
        # ID Convention: moment_{SUBTYPE}_{context}_{disambiguator}
        # Example: moment_CREATE_physics-tick-runner_a7
        node_type: moment
        type: protocol_create
        prose: "Created space {space_name} ({space_type})"
        status: spoken
        # ━━━ ATTRIBUTE EXPLANATIONS ━━━
        #
        # id: "moment_CREATE_{module_name}_{timestamp_short}"
        #   WHAT: Unique ID with subtype and short hash
        #   WHY: Moments are ordered by creation time, SUBTYPE for scanning
        #   FORMAT: moment_{SUBTYPE}_{context}_{hash}
        #
        # node_type: moment
        #   WHAT: Point-in-time event record
        #   WHY: Creates history that can be queried
        #   CONTRAST: narratives are persistent, moments are events
        #
        # type: protocol_create
        #   WHAT: Categorizes this moment type
        #   WHY: Enables queries like "show all creation events"
        #   OTHER_TYPES: sync_update, decision, escalation_raised
        #
        # prose: "Created space..."
        #   WHAT: Human-readable description
        #   WHY: Displayed in activity feeds and history
        #   FORMAT: Past tense, specific about what happened
        #
        # status: spoken
        #   WHAT: Moment state
        #   WHY: "spoken" = articulated/public, "internal" = private thought
        #   OPTIONS: spoken, internal, pending

    links:
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # LINK: Parent Contains Child
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - type: contains
        from: "{parent_space}"
        to: "{space_id}"
        condition: "{parent_space} != ''"
        # ━━━ LINK EXPLANATION ━━━
        #
        # type: contains
        #   WHAT: Parent-child relationship
        #   WHY: Establishes hierarchy - "area contains modules"
        #   QUERY: "What spaces are in area X?" follows contains
        #   DIRECTION: from=parent, to=child
        #
        # condition: "{parent_space} != ''"
        #   WHAT: Only create link if parent specified
        #   WHY: Root spaces have no parent
        #   ALTERNATIVE: Could link to implicit "root" space

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # LINK: Actor Expresses Moment
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - type: expresses
        from: "{actor_id}"
        to: "moment_CREATE_{module_name}_{timestamp_short}"
        # ━━━ LINK EXPLANATION ━━━
        #
        # type: expresses
        #   WHAT: Attribution link
        #   WHY: Records who/what created this moment
        #   QUERY: "What did agent X do?" follows expresses
        #   DIRECTION: from=actor, to=moment

      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      # LINK: Moment About Space
      # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
      - type: about
        from: "moment_CREATE_{module_name}_{timestamp_short}"
        to: "{space_id}"
        # ━━━ LINK EXPLANATION ━━━
        #
        # type: about
        #   WHAT: Topic/subject relationship
        #   WHY: Records what the moment relates to
        #   QUERY: "What happened to space X?" follows about
        #   DIRECTION: from=moment/narrative, to=subject

    next: call_handoff

  call_handoff:
    type: call_protocol
    protocol: completion_handoff
    inputs:
      space_id: "{space_id}"
      task_id: "define_space_{space_id}"
    next: $complete

output:
  cluster:
    nodes:
      - space (1)
      - moment_create (1)
    links:
      - contains (parent → child, conditional)
      - expresses (actor → moment)
      - about (moment → space)
  summary: "Created space {space_id} ({space_type})"
  returns:
    space_created: "{space_id}"
    moment: "moment_CREATE_{module_name}_{timestamp_short}"

# ID Convention Reference:
# See docs/schema/PATTERNS_Schema.md section 3 for full ID format specification.
# Format: {node-type}_{SUBTYPE}_{instance-context}_{disambiguator}
