# Graph Engine Project Schema
# EXTENDS: docs/schema/schema.yaml (authoritative base schema)
#
# This schema adds Graph Engine-specific type enums.
# Base schema defines: node_type (5 values), type (free string)
# This schema constrains `type` to game-specific values.
#
# v1.2 CHANGES:
#   - 9 link types: 4 energy carriers + 5 structural
#   - Energy carriers: expresses, about, relates, attached_to
#   - Structural: contains, leads_to, sequence, primes, can_become
#   - Semantic properties: name, role, direction on all links
#   - NO DECAY: link cooling replaces decay (30% drain + 10% strength)
#   - Hot/cold filtering via heat_score = energy × weight
#   - Migration: 14 old types → 9 new types
#
# v1.1 CHANGES (from base schema):
#   - Node weight/energy now unbounded (0-∞)
#   - Links: weight/strength/energy/polarity REMOVED
#   - Links: conductivity ADDED (0-1, percentage of energy flow)
#   - Link types collapsed: at→contains, said→expresses, then→sequence
#   - relates links now have a_emotions/b_emotions
#
# Used by check_health.py and test_schema.py for validation.

nodes:
  Actor:
    required:
      - id
      - name
    optional:
      - type           # player, companion, major, minor, background
      - gender         # female, male (default: male)
      - alive          # boolean
      - face           # young, scarred, weathered, gaunt, hard, noble
      - voice_tone     # quiet, sharp, warm, bitter, measured, fierce
      - voice_style    # direct, questioning, sardonic, gentle, blunt
      - approach       # direct, cunning, cautious, impulsive, deliberate
      - values         # JSON array: loyalty, survival, honor, ambition, faith, etc.
      - flaw           # pride, fear, greed, wrath, doubt, etc.
      - backstory_family
      - backstory_childhood
      - backstory_wound
      - backstory_why_here
      - modifiers      # JSON array
      - detail         # Extended narrative text for rich descriptions
    enums:
      type:
        - player
        - companion
        - major
        - minor
        - background
      gender:
        - male
        - female
      face:
        - young
        - scarred
        - weathered
        - gaunt
        - hard
        - noble
      voice_tone:
        - quiet
        - sharp
        - warm
        - bitter
        - measured
        - fierce
      voice_style:
        - direct
        - questioning
        - sardonic
        - gentle
        - blunt
      approach:
        - direct
        - cunning
        - cautious
        - impulsive
        - deliberate
      flaw:
        - pride
        - fear
        - greed
        - wrath
        - doubt
        - null

  Space:
    required:
      - id
      - name
    optional:
      - historical_name
      - type           # region, city, hold, village, monastery, crossing, road, wilderness, forest, ruin, camp, etc.
      - lat
      - lng
      - weather
      - mood
      - details        # JSON array (legacy)
      - modifiers      # JSON array
      - detail         # Extended narrative text for rich descriptions
    enums:
      type:
        - region
        - city
        - town
        - hold
        - village
        - monastery
        - abbey
        - crossing
        - road
        - wilderness
        - forest
        - ruin
        - camp
        - holy_well
        - standing_stones
        - hill
        - crossroads

  Thing:
    required:
      - id
      - name
    optional:
      - type           # weapon, armor, document, letter, relic, treasure, title, land, token, provisions
      - portable       # boolean
      - significance   # mundane, personal, political, sacred, legendary
      - quantity       # integer
      - description
      - modifiers      # JSON array
      - detail         # Extended narrative text for rich descriptions
    enums:
      type:
        - weapon
        - armor
        - document
        - letter
        - relic
        - treasure
        - title
        - land
        - token
        - provisions
      significance:
        - mundane
        - personal
        - political
        - sacred
        - legendary

  Narrative:
    required:
      - id
      - name
      - content
    optional:
      - interpretation
      - type           # memory, account, rumor, reputation, identity, bond, oath, debt, blood, enmity, love, service, ownership, claim, control, origin, belief, prophecy, lie, secret
      - about_actors      # JSON array (renamed from about_characters)
      - about_spaces      # JSON array (renamed from about_places)
      - about_things      # JSON array
      - about_relationship # JSON array
      - tone           # bitter, proud, shameful, defiant, mournful, cold, righteous, hopeful, fearful, warm, dark, sacred
      - voice_style
      - voice_phrases  # JSON array
      - weight         # float 0-1 (computed)
      - focus          # float 0.1-3.0
      - truth          # float 0-1 (director only)
      - narrator_notes
      - occurred_at    # When the event occurred (e.g., "Day 12, dawn")
      # NOTE: occurred_where is now OCCURRED_AT link to Space, not an attribute
      - detail         # Extended narrative text for rich descriptions
    enums:
      type:
        - memory
        - account
        - rumor
        - rumour
        - reputation
        - identity
        - bond
        - oath
        - debt
        - blood
        - enmity
        - love
        - service
        - ownership
        - claim
        - control
        - origin
        - belief
        - prophecy
        - lie
        - secret
      tone:
        - bitter
        - proud
        - shameful
        - defiant
        - mournful
        - cold
        - righteous
        - hopeful
        - fearful
        - warm
        - dark
        - sacred

  Moment:
    required:
      - id
    optional:
      - name
      - content        # Moment content/description
      - status         # active, resolved, pending
      - energy         # float >= 0
      - weight         # float >= 0
      - duration_minutes  # int, for radiation rate
      - detail         # Extended narrative text
    enums:
      status:
        - active
        - resolved
        - pending

links:
  # ---------------------------------------------------------------------------
  # v1.2 LINK TYPES (9 total)
  # Energy carriers (4): expresses, about, relates, attached_to
  # Structural (5): contains, leads_to, sequence, primes, can_become
  #
  # All links have: name, role, direction (semantic properties)
  # ---------------------------------------------------------------------------
  # ==========================================================================
  # ENERGY CARRIER LINKS (4)
  # ==========================================================================

  EXPRESSES:
    # Actor expresses a Moment (speech, action, emotion)
    # Migration: SAID → EXPRESSES
    from: Actor
    to: Moment
    required: []
    optional:
      - name           # Link label (e.g., "says", "does", "feels")
      - role           # originator, believer, witness, subject, creditor, debtor
      - direction      # support, oppose, elaborate, subsume, supersede
      - conductivity   # float 0-1 (percentage of energy flow)
      - detail         # Extended narrative text
    enums:
      role:
        - originator
        - believer
        - witness
        - subject
      direction:
        - support
        - oppose
        - elaborate

  ABOUT:
    # Narrative/Moment is about a node (subject reference)
    # Migration: OCCURRED_AT → ABOUT
    from: [Narrative, Moment]
    to: [Actor, Space, Thing, Narrative, Moment]
    required: []
    optional:
      - name           # Link label
      - role           # originator, believer, witness, subject
      - direction      # support, oppose, elaborate, subsume, supersede
      - conductivity   # float 0-1
      - detail         # Extended narrative text
    enums:
      role:
        - originator
        - believer
        - witness
        - subject
      direction:
        - support
        - oppose
        - elaborate
        - subsume
        - supersede

  RELATES:
    # Bidirectional semantic relation with emotions
    # Migration: BELIEVES, NARRATIVE_LINK → RELATES (with role)
    from: [Actor, Space, Thing, Narrative, Moment]
    to: [Actor, Space, Thing, Narrative, Moment]
    required: []
    optional:
      - name           # Link label (e.g., "believes", "fears", "loves")
      - role           # originator, believer, witness, subject, creditor, debtor
      - direction      # support, oppose, elaborate, subsume, supersede
      - a_emotions     # List[[string, float]] - emotions from node_a perspective
      - b_emotions     # List[[string, float]] - emotions from node_b perspective
      - conductivity   # float 0-1
      - detail         # Extended narrative text
    enums:
      role:
        - originator
        - believer
        - witness
        - subject
        - creditor
        - debtor
      direction:
        - support
        - oppose
        - elaborate
        - subsume
        - supersede

  ATTACHED_TO:
    # Physical attachment (carrying, located at)
    # Migration: CARRIES, LOCATED_AT → ATTACHED_TO
    from: [Actor, Thing]
    to: [Actor, Thing, Space]
    required: []
    optional:
      - name           # Link label (e.g., "carries", "located at")
      - role           # subject, creditor, debtor
      - direction      # support, oppose
      - hidden         # float 0-1 (visibility)
      - conductivity   # float 0-1
      - detail         # Extended narrative text
    enums:
      role:
        - subject
        - creditor
        - debtor
      direction:
        - support
        - oppose

  # ==========================================================================
  # STRUCTURAL LINKS (5)
  # ==========================================================================

  CONTAINS:
    # Spatial containment (Space contains Actor/Thing/Space)
    # Migration: AT → CONTAINS (reversed direction)
    from: Space
    to: [Space, Actor, Thing]
    required: []
    optional:
      - name           # Link label
      - role           # subject
      - direction      # support
      - present        # float 0-1 (for actors)
      - visible        # float 0-1 (for actors)
      - conductivity   # float 0-1
      - detail         # Extended narrative text

  LEADS_TO:
    # Spatial connection between spaces
    # Migration: CONNECTS → LEADS_TO
    from: Space
    to: Space
    required: []
    optional:
      - name           # Link label (e.g., "road to", "path through")
      - role           # subject
      - direction      # support
      - path_km        # float
      - path_hours     # float
      - path_terrain   # roman_road, moor, forest, river_crossing, track, marsh
      - conductivity   # float 0-1
      - detail         # Extended narrative text
    enums:
      path_terrain:
        - roman_road
        - moor
        - forest
        - river_crossing
        - track
        - marsh

  SEQUENCE:
    # Moment sequence (temporal ordering)
    # Migration: THEN → SEQUENCE
    from: Moment
    to: Moment
    required:
      - tick           # int
    optional:
      - name           # Link label
      - conductivity   # float 0-1
      - detail         # Extended narrative text

  PRIMES:
    # Priming relationship (anticipation, setup)
    from: [Narrative, Moment, Actor]
    to: [Actor, Moment, Space]
    required: []
    optional:
      - name           # Link label
      - role           # originator, witness
      - direction      # support, oppose
      - lag_ticks      # int (delay before effect)
      - conductivity   # float 0-1
      - detail         # Extended narrative text
    enums:
      role:
        - originator
        - witness
      direction:
        - support
        - oppose

  CAN_BECOME:
    # Moment branching possibilities
    # Migration: CAN_LEAD_TO → CAN_BECOME
    from: Moment
    to: Moment
    required: []
    optional:
      - name           # Link label
      - trigger        # player, auto, wait
      - conductivity   # float 0-1
      - detail         # Extended narrative text
    enums:
      trigger:
        - player
        - auto
        - wait

  # ==========================================================================
  # DEPRECATED (v1.1 → v1.2 migration)
  # These are kept for backwards compatibility during migration only
  # ==========================================================================

  BELIEVES:
    # DEPRECATED: Use RELATES with role: believer
    deprecated: true
    from: Actor
    to: Narrative
    required: []
    optional:
      - heard          # float 0-1
      - believes       # float 0-1
      - doubts         # float 0-1
      - conductivity   # float 0-1
    enums:
      source:
        - witnessed
        - told
        - inferred
        - assumed
        - taught

  AT:
    # DEPRECATED: Use CONTAINS with reversed direction
    deprecated: true
    from: Actor
    to: Space
    required: []
    optional:
      - present        # float 0-1
      - visible        # float 0-1
      - conductivity   # float 0-1

  CARRIES:
    # DEPRECATED: Use ATTACHED_TO
    deprecated: true
    from: Actor
    to: Thing
    required: []
    optional:
      - carries        # float 0-1
      - carries_hidden # float 0-1
      - conductivity   # float 0-1

  LOCATED_AT:
    # DEPRECATED: Use ATTACHED_TO
    deprecated: true
    from: Thing
    to: Space
    required: []
    optional:
      - located        # float 0-1
      - hidden         # float 0-1
      - conductivity   # float 0-1

  CONNECTS:
    # DEPRECATED: Use LEADS_TO
    deprecated: true
    from: Space
    to: Space
    required: []
    optional:
      - path_km        # float
      - path_hours     # float
      - conductivity   # float 0-1
